import json
import urllib.request
from llm_client import ScreeningLLMClient
from config.paths import ProjectPaths

import os 

# this code is mostly generated by AI, with minor tweaks by me

def get_openrouter_pricing(model_name: str) -> tuple[float, float]:
    """Fetches dynamic pricing per 1M tokens (input, output) in USD from OpenRouter."""
    try:
        req = urllib.request.Request("https://openrouter.ai/api/v1/models")
        with urllib.request.urlopen(req, timeout=10) as response:
            models_data = json.loads(response.read().decode())
            for model in models_data.get("data", []):
                if model["id"] == model_name:
                    # OpenRouter API returns cost per single token
                    prompt_price = float(model["pricing"]["prompt"]) * 1_000_000
                    completion_price = float(model["pricing"]["completion"]) * 1_000_000
                    return prompt_price, completion_price
    except Exception as e:
        print(f"Warning: Could not fetch live pricing for '{model_name}' ({e}). Using fallback.")
    
    return 0.14, 0.28  # Fallback prices

def calculate_metrics():
    paths = ProjectPaths()
    
    with open(paths.ground_truth_dataset, 'r', encoding='utf-8') as f:
        dataset = json.load(f)
        
    client = ScreeningLLMClient()
    client.load_anchors(paths.manual_dataset_json)
    
    TP, FP, TN, FN = 0, 0, 0, 0
    
    for key, data in dataset.items():
        ground_truth = data.get("is_desk_reject")
        forum_id = data.get("forum_id")
       
        status_folder = "desk-rejects" if ground_truth == 1 else "accepted"    
        if not os.path.exists(paths.get_evaluation_pdf_path(forum_id,status_folder)) : 
            continue
        print(f"\nEvaluating {forum_id}...")
        
        
        result = client.evaluate_paper(forum_id, status_folder=status_folder)
        prediction = result["is_desk_reject"]
        
        if ground_truth == 1 and prediction == 1:
            TP += 1
        elif ground_truth == 0 and prediction == 1:
            FP += 1
        elif ground_truth == 0 and prediction == 0:
            TN += 1
        elif ground_truth == 1 and prediction == 0:
            FN += 1

    precision = TP / (TP + FP) if (TP + FP) > 0 else 0.0
    recall = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0
    
    print(f"\nFetching live pricing for model: {client.model_name}...")
    INPUT_PRICE_PER_1M_USD, OUTPUT_PRICE_PER_1M_USD = get_openrouter_pricing(client.model_name)
    print("the price for gemini flash v3,5 : input , output " , INPUT_PRICE_PER_1M_USD , " " , OUTPUT_PRICE_PER_1M_USD)
    EUR_TO_USD = 1.05 
    
    total_in = client.total_input_tokens
    total_out = client.total_output_tokens
    
    total_cost_usd = (total_in / 1_000_000 * INPUT_PRICE_PER_1M_USD) + (total_out / 1_000_000 * OUTPUT_PRICE_PER_1M_USD)
    total_cost_eur = total_cost_usd / EUR_TO_USD
    tokens_per_euro = (total_in + total_out) / total_cost_eur if total_cost_eur > 0 else 0
    print("\n" + "="*45)
    print("      PIPELINE EVALUATION METRICS")
    print("="*45)
    print(f"Model Evaluated:      {client.model_name}")
    print(f"Prices Used (1M USD): In: ${INPUT_PRICE_PER_1M_USD:.4f} | Out: ${OUTPUT_PRICE_PER_1M_USD:.4f}")
    print("-" * 45)
    print(f"True Positives (TP):  {TP}")
    print(f"False Positives (FP): {FP}")
    print(f"True Negatives (TN):  {TN}")
    print(f"False Negatives (FN): {FN}")
    print("-" * 45)
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1 Score:  {f1:.4f}")
    print("-" * 45)
    print(f"Total Input Tokens:   {total_in:,}")
    print(f"Total Output Tokens:  {total_out:,}")
    print(f"Total Cost (EUR):    €{total_cost_eur:.4f}")
    print(f"Tokens per Euro:      {tokens_per_euro:,.0f}")
    print("="*45)

if __name__ == "__main__":
    calculate_metrics()