import os
import json
from openai import OpenAI
from dotenv import load_dotenv
import fitz
import base64
from prompts import *

from preprocessing import extract_pdf_data # reuse some methods

# this code was partially generated with the assistance of GitHub Copilot and Google Gemini, and thoroughly reviewed and adjusted by me.

class ScreeningLLMClient:
    # class to reuse the network connection + track token usage

    def __init__(self, model_name: str = "deepseek/deepseek-v4-flash"):
        
        script_dir = os.path.dirname(os.path.abspath(__file__))
        dotenv_path = os.path.join(script_dir, '..', '.env')
        load_dotenv(dotenv_path)

        api_key = os.getenv("API_KEY")
        if not api_key:
            raise ValueError("API_KEY is missing from the .env file.")

        self.client = OpenAI(base_url="https://openrouter.ai/api/v1"
                            ,api_key=api_key)
        self.model_name = model_name
        
        # Anchor dataset dictionary acting as the in-context evaluation standard
        self.anchor_data = {}
        
        # State counters to keep track of total token investments across a batch run
        self.total_input_tokens = 0
        self.total_output_tokens = 0

    def load_anchors(self, labels_json_path: str):
        """
        Loads the labeled dataset JSON file
        
        Args:
            labels_json_path: Path to the JSON map of paper IDs to their ground truth classifications.
        """
        if not os.path.exists(labels_json_path):
            print(f"Warning: Anchor label file not found at {labels_json_path}. Proceeding without anchors.")
            return

        with open(labels_json_path, 'r', encoding='utf-8') as f:
            self.anchor_data = json.load(f)
            print("Anchors loaded succesfully...")
        

    def _build_anchor_instruction_string(self) -> str:
        if not self.anchor_data:
            return "No examples provided for this run."
            
        anchor_str = "Use these verified historical benchmarks. Verdicts: 0=Accepted, 1=Desk Reject:\n\n"
        
        # Limit to a maximum of 3 key anchors to save tokens
        for id, data in list(self.anchor_data.items())[:3]: 
            anchor_str += f"=== ANCHOR CASE: {id} (VERDICT: {data['is_desk_reject']}) ===\n"
            anchor_str += f"REASON: {data['rejection_category']}\n"
            
            raw_text = data.get('parsed_text', '')

            if 'raw_comments' in data and data['raw_comments'] != "None":
                anchor_str += f"SPECIFIC VIOLATION FOUND: {data['raw_comments']}\n"
            
            # Extract the structural fragments
            front_matter = raw_text[:2000] # First ~500 words for anonymity checking
            
            # Find references to check page-limit behavior
            ref_index = raw_text.lower().rfind("references")
            back_matter = raw_text[ref_index:ref_index + 3000] if ref_index != -1 else raw_text[-3000:]
            
            anchor_str += f"[START OF PAPER FRAGMENT]\n{front_matter}\n[... TRUNCATED BODY ...]\n{back_matter}\n[END OF PAPER FRAGMENT]\n"
            anchor_str += "=========================================\n\n"
        
        return anchor_str
    

    # --------------------------------------------

    # the following helper function is entirely generated by AI
    @staticmethod
    def get_page_as_base64_image(pdf_path: str, page_num: int, zoom: float = 2.0) -> str: 
        """
        Renders a specific 1-based page number from a PDF into a crisp PNG 
        and returns its Base64 encoded string wrapper.
        """
        doc = fitz.open(pdf_path)
        
        # Check if the requested page even exists in the document
        if page_num > doc.page_count:
            doc.close()
            raise IndexError(f"Requested page {page_num}, but paper only has {doc.page_count} pages.")
        
        # 1-based page number to 0-based index conversion
        page_index = page_num - 1
        page = doc.load_page(page_index)
        
        
        # Using a Matrix to scale the resolution. 
        # zoom=2.0 doubles the crispness of the rendered text so the LLM can read it easily.
        matrix = fitz.Matrix(zoom, zoom)
        pix = page.get_pixmap(matrix=matrix)
        
        # Convert pixel map directly to standard PNG bytes in memory
        image_bytes = pix.tobytes("png")
        
        doc.close()
        
        # Encode bytes to a clean utf-8 Base64 string wrapper
        base64_string = base64.b64encode(image_bytes).decode("utf-8")
        return base64_string

    def step_1(self, pdf_path, evaluation_context : list) : # page count 
        # first step, we check the page count, if an IndexError is raised that means the page doesnt even exist and we should be clear
        # else we append the response to converstation_history
        
        try : 
            page_9_img = self.get_page_as_base64_image(pdf_path, 9)
            page_10_img = self.get_page_as_base64_image(pdf_path, 10)


            step_1_content = [
                {"type": "text",
                    "text": STEP_PROMPTS["step_1_visual_boundary"]
                },
                {
                    "type":"image_url",
                    "image_url": {"url": f"data:image/png;base64,{page_9_img}"}
                },
                {
                    "type":"image_url",
                    "image_url": {"url": f"data:image/png;base64,{page_10_img}"}
                }
            ]
            evaluation_context.append({"role": "user", "content" : step_1_content})
        except IndexError: 
            print("Error in step 2, selected random page doesn't exist!\n Step 2 verification is skipped.")
            return
        except Exception as e:
            print(f"Error in Step 1 : {e} .\n Step 1 Verification is skipped !")
         

    def step_2(self, pdf_path, evaluation_context : list) : # formating , margins
        try : 
            random_page_img = self.get_page_as_base64_image(pdf_path, 4)    

            step_2_content = [
                {   
                    "type": "text",
                    "text": STEP_PROMPTS["step_2_layout_compliance"]
                },
                {
                    "type":"image_url",
                    "image_url": {"url": f"data:image/png;base64,{random_page_img}"}
                }
            ]
            evaluation_context.append({"role": "user", "content" : step_2_content})       
        except IndexError: 
            print("Error in step 2, selected random page doesn't exist!\n Step 2 verification is skipped.")
            return 
        except Exception as e:
            print(f"Error in Step 2 : {e} .\n Step 2 Verification is skipped !")


    def step_3(self, pdf_path, evaluation_context : list) : # deals with parsed text, checks anonymity ( names and links ), citations, scientific integrity ( attempts to do prompt injection ) 
        try:
            raw_text ,_ = extract_pdf_data(pdf_path)

            step_3_content = [{   
                    "type": "text",
                    "text": STEP_PROMPTS["step_3_textual_integrity"]
                },
                {
                    "type": "text",
                    "text": raw_text
                }]
            evaluation_context.append({"role": "user", "content" : step_3_content})
        except Exception as e:
            print(f"Error in Step 3 : {e} .\n Step 3 Verification is skipped !")

        


    def evaluate_paper(self, paper_forum_id: str) -> dict:
       
        anchor_context = self._build_anchor_instruction_string()
        print("Successfully built the anchor instruction string...")

        script_dir = os.path.dirname(os.path.abspath(__file__))
        target_dir = os.path.join(script_dir,"..","data", "to_evaluate", "rejected")
        file_path =  os.path.join(target_dir,f"{paper_forum_id}.pdf")
        evaluation_context=[]
        print("[Step 1 of building the Evaluation context]")
        self.step_1(file_path,evaluation_context)
        print("Step 1 successfully completed...")
        print("[Step 2 of building the Evaluation context]")
        self.step_2(file_path,evaluation_context)
        print("Step 2 successfully completed...")
        print("[Step 3 of building the Evaluation context]")
        self.step_3(file_path,evaluation_context)
        print("Step 3 successfully completed...")

        
        messages = [{"role":"system", "content": SYSTEM_PROMPTS['general_system']}] + evaluation_context

        try:
            response = self.client.chat.completions.create(
                model=self.model_name,
                messages=messages,
                response_format={"type": "json_object"},
                temperature=0.0 # supposedly makes the model more deterministic.
            )
            
            if response.usage:
                self.total_input_tokens += response.usage.prompt_tokens
                self.total_output_tokens += response.usage.completion_tokens

            return json.loads(response.choices[0].message.content)

        except Exception as e:
            return {
                "is_desk_reject": 0,
                "rejection_category": "API_EXECUTION_ERROR",
                "detailed_justification": f"exception detected: {str(e)}",
                "detected_external_links": []
            }

    def print_usage_report(self):
        """Prints the accumulated token statistics."""
        print("\n--- API COMPUTE USAGE REPORT ---")
        print(f"Total Input Tokens Tracked: {self.total_input_tokens}")
        print(f"Total Output Tokens Tracked: {self.total_output_tokens}")
        print("---------------------------------")


if __name__ == "__main__":
    print("Testing the anchor-driven screening class...")
    deepseek = "deepseek/deepseek-v4-flash"
    gemini_flash = "google/gemini-2.5-flash"
    try:
        evaluator = ScreeningLLMClient(model_name=gemini_flash)

        script_dir = os.path.dirname(os.path.abspath(__file__))

        dataset_path = os.path.join(script_dir, "..", "data", "processed", "labeled_dataset.json")
        manual_dataset_path = os.path.join(script_dir,"..","data","manually_labeled_dataset.json")
        evaluator.load_anchors(labels_json_path=manual_dataset_path)
        

        print(evaluator.evaluate_paper('jHzWNnVQWU'))
        evaluator.print_usage_report()

    except ValueError as err:
        print(f"Failed to bootstrap pipeline: {err}")